#ifndef __MOUSEBUTTONCODES_H__
#define __MOUSEBUTTONCODES_H__

// from GLFW/glfw3.h
#define ZYKLON_MOUSE_BUTTON_1         0
#define ZYKLON_MOUSE_BUTTON_2         1
#define ZYKLON_MOUSE_BUTTON_3         2
#define ZYKLON_MOUSE_BUTTON_4         3
#define ZYKLON_MOUSE_BUTTON_5         4
#define ZYKLON_MOUSE_BUTTON_6         5
#define ZYKLON_MOUSE_BUTTON_7         6
#define ZYKLON_MOUSE_BUTTON_8         7
#define ZYKLON_MOUSE_BUTTON_LAST      ZYKLON_MOUSE_BUTTON_8
#define ZYKLON_MOUSE_BUTTON_LEFT      ZYKLON_MOUSE_BUTTON_1
#define ZYKLON_MOUSE_BUTTON_RIGHT     ZYKLON_MOUSE_BUTTON_2
#define ZYKLON_MOUSE_BUTTON_MIDDLE    ZYKLON_MOUSE_BUTTON_3
#endif // __MOUSEBUTTONCODES_H__